In [2]:
#### Linear Algebra_Project04_2022
# Problem: Diagnalization

import numpy as np
from numpy.linalg import eig

#A = np.array([(1, 0, 0, 0), (0, -2, 0, 0),(0, 0, 2, 0), (0, 0, 0, 3)])
A = np.array([(1, 1, 1, 1), (2, 1, -1, -2),(1, -1, -1, 1), (1, -2, 2, -1)])

# STEP1: find eigenvalues, eigenvectors and matrix P
eigValue, eigVector = eig(A)
for i in range(0, 4):
    print("λ = ", eigValue[i], f"\tp{i + 1}", "= ", eigVector.T[i])
P = eigVector
print("\nP =\n",P)

# STEP2: find the inverse of matrix P
I = np.identity(4)
TMP = P.copy()
for i in range(4):
    # Introduce a leading 1    
    # Check if there's zero in main diagonal
    for d in range(i, 4): 
        head = TMP[d][d]
        if(head == 0):
            c = 1
            # Find the nonzero leading element
            while (d + c < 4) and (TMP[d + c][d] == 0):
                c += 1
                
            # Matrix is singular
            if(d + c == 4):
                sys.exit("matrix not invertible")  
            
            # Interchange
            TMP[[d, d + c]] = TMP[[d + c, d]]
            I[[d, d + c]] = I[[d + c, d]]

    head = TMP[i][i]
    for j in range(4):
        TMP[i][j] = TMP[i][j] / head
        I[i][j] = I[i][j] / head

    # Foward phase      
    for j in range(i + 1, 4):
        ratio = TMP[j][i] / TMP[i][i]
        for k in range(0, 4):
            TMP[j][k] = TMP[j][k] - ratio * TMP[i][k]
            I[j][k] = I[j][k] - ratio * I[i][k]

# Backward phase
for i in range(4 - 1, -1, -1):
    for j in range(i - 1, -1, -1):
        ratio = TMP[j][i] / TMP[i][i]
        if ratio == 0:
                continue
        for k in range(4 - 1, -1, -1):
            TMP[j][k] = TMP[j][k] - ratio * TMP[i][k]
            I[j][k] = I[j][k] - ratio * I[i][k]
            
print("\nP^(-1) =\n", I)

# STEP3: find the diagonal matrix D
D = np.array(I.dot(A).dot(P))
np.set_printoptions(suppress = True)
print("\nD =\n", D)
# STEP4: find the inverse of matrix P
RES = np.identity(4)
tmp = 0
#D=np.diag(eigValue)
d1 = D[0][0]
d2 = D[1][1]
d3 = D[2][2]
d4 = D[3][3]

#for i in range(0, 99):
D[0][0] = pow(d1,100)
D[1][1] = pow(d2,100) 
D[2][2] = pow(d3,100)
D[3][3] = pow(d4,100)
#A^100=PD^100P^(-1)
RES=P@D@I
        
print("\nA^100 =\n", RES)



λ =  2.8284271247461885 	p1 =  [-0.15622986  0.68963195 -0.37717224 -0.59811462]
λ =  2.2360679774997902 	p2 =  [ 0.69455348 -0.13264791  0.42925766  0.56190557]
λ =  -2.828427124746192 	p3 =  [-0.37717224  0.59811462  0.15622986  0.68963195]
λ =  -2.23606797749979 	p4 =  [ 0.42925766 -0.56190557 -0.69455348 -0.13264791]

P =
 [[-0.15622986  0.69455348 -0.37717224  0.42925766]
 [ 0.68963195 -0.13264791  0.59811462 -0.56190557]
 [-0.37717224  0.42925766  0.15622986 -0.69455348]
 [-0.59811462  0.56190557  0.68963195 -0.13264791]]

P^(-1) =
 [[ 0.75434448  1.06680419 -0.31245971 -0.44188477]
 [ 1.25645904  0.56190557  0.29660975  0.13264791]
 [-0.31245971  0.44188477 -0.75434448  1.06680419]
 [ 0.29660975 -0.13264791 -1.25645904  0.56190557]]

D =
 [[ 2.82842712 -0.         -0.          0.        ]
 [-0.          2.23606798 -0.          0.        ]
 [ 0.          0.         -2.82842712 -0.        ]
 [ 0.         -0.          0.         -2.23606798]]

A^100 =
 [[ 8.88281511e+34 -4.75749231

In [12]:
A=pow(2.0,100)
A

1.2676506002282294e+30