In [74]:
import numpy as np

In [75]:
for i in range(10,20,3):
    print(i)

10
13
16
19


## 語法
for迴圈補充:range(起始值,結束值,遞增(減)值)。

In [76]:
for i in 'apple':
    print(i)

a
p
p
l
e


## 語法
for迴圈補充:可以針對Iterable(可疊代的)物件來進行讀取，Python內建幾個常用的Iterable物件，像是String(字串)、List(串列)、Tuples(元組)、Dictionary(字典)等。

In [72]:
for i in range(3):
    for j in range(3):
        print(i,j)

0 0
0 1
0 2
1 0
1 1
1 2
2 0
2 1
2 2


## 語法
for迴圈補充:Nested Loops(巢狀迴圈)，迴圈內又有迴圈。

In [29]:
print(np.arange(1,10))
print(np.arange(1,10,2,float))
print(np.arange(1,11,2,float))
print(type(np.arange(1,11,2,float)))

[1 2 3 4 5 6 7 8 9]
[1. 3. 5. 7. 9.]
[1. 3. 5. 7. 9.]
<class 'numpy.ndarray'>


## numpy套件
numpy.arange(start,stop,step,dtype=None, *, like=None):
產生一個等差數列的陣列。<br>
start : 從某數開始，預設為 0<br>
stop : 到某數停止(不包含)<br>
step : 間隔多少<br>
dtype : bool(布林值), int(整數), float(浮點數), complex(複數)<br>

In [41]:
print(np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]]),'\n')
print(np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]],-1),'\n')
print(np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]],1))

[[1 2 3]
 [0 5 6]
 [0 0 9]
 [0 0 0]] 

[[ 1  2  3]
 [ 4  5  6]
 [ 0  8  9]
 [ 0  0 12]] 

[[0 2 3]
 [0 0 6]
 [0 0 0]
 [0 0 0]]


In [42]:
print(np.tril([[1,2,3],[4,5,6],[7,8,9],[10,11,12]]),'\n')
print(np.tril([[1,2,3],[4,5,6],[7,8,9],[10,11,12]],-1),'\n')
print(np.tril([[1,2,3],[4,5,6],[7,8,9],[10,11,12]],1))

[[ 1  0  0]
 [ 4  5  0]
 [ 7  8  9]
 [10 11 12]] 

[[ 0  0  0]
 [ 4  0  0]
 [ 7  8  0]
 [10 11 12]] 

[[ 1  2  0]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


## numpy套件
numpy.triu(m, k=0):取得上三角矩陣，返回的值其中元素 k-th 對角線包含以下歸零。<br>
numpy.tril(m, k=0):取得下三角矩陣，返回的值其中元素 k-th 對角線包含以上歸零。<br>
k默認為0

In [59]:
U=np.array([-2, 1, 2, 0, 3, -2, 0, 0, 4])
print(U[1:6])
print(U[1:6:2])
print(U[:-1],'\n')
U=U.reshape(3,3)
print(U,'\n')
print(U[2,1:3])
print(type(U[2,1:3]))

[ 1  2  0  3 -2]
[ 1  0 -2]
[-2  1  2  0  3 -2  0  0] 

[[-2  1  2]
 [ 0  3 -2]
 [ 0  0  4]] 

[0 4]
<class 'numpy.ndarray'>


## 語法
python slice用法:[起點 : 終點(不包含) : 間隔]，預設值為 [0: 提取到最後一個:1]。<br>
[:-1]表示為到最後一個元素(不包含)<br>

In [62]:
a = np.array([1, 2])
b = np.array([3, 4])
c = np.array([5, 6])
np.concatenate((a,b,c))

array([1, 2, 3, 4, 5, 6])

In [73]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
print(a,b,'\n')
print(np.concatenate((a, b), axis=0),'\n')
print(np.concatenate((a, b.T), axis=1),'\n')
print(np.concatenate((a, b), axis=None))

[[1 2]
 [3 4]] [[5 6]] 

[[1 2]
 [3 4]
 [5 6]] 

[[1 2 5]
 [3 4 6]] 

[1 2 3 4 5 6]


## numpy套件
numpy.concatenate((a1, a2, ...), axis=0, out=None, dtype=None, casting="same_kind"):用來拼接array，可為多組或多維。<br>
一維陣列<br>
axis的值不影響結果<br>
二維陣列<br>
axis=0 按照行拼接<br>
axis=1 按照列拼接<br>
axis=None 使變成一維陣列<br>
axis=0為預設值