In [1]:
import numpy as np

In [2]:
A = np.array(([-3, 2, -1], [6, -6, 7], [3, -4, 4]), int)
Ab = np.array(A, copy=True)
m,n=Ab.shape  
#step1:G.E. to upper triangular matrix to get U!  
for i in range(0, n):
    for k in range(i+1, n):
        Ab[k][i:n] = Ab[k][i:n] - (Ab[i][i:n] * (Ab[k][i] / Ab[i][i]))
        #print(i, k, Ab[k][i:n+1], Ab[i][i:n+1], Ab[k][i], Ab[i][i], '\n')
        
print("Step1's conclusion:\n", Ab, '\n')

#step2:get L!
L=np.zeros((3,3),int)
for i in range(0,n):
    for j in range (0,i+1):   
        L[i,j]=(A[i,j]-L[i].dot(Ab[:,j]))/Ab[j,j]   
#【Answer】
print("L:")
print(L)
print("U:")
print(Ab)
#print('Step2 to Answer:\nx =', x)

Step1's conclusion:
 [[-3  2 -1]
 [ 0 -2  5]
 [ 0  0 -2]] 

L:
[[ 1  0  0]
 [-2  1  0]
 [-1  1  1]]
U:
[[-3  2 -1]
 [ 0 -2  5]
 [ 0  0 -2]]


In [3]:
#AA.inverse =I
#Ly=b=Identity matrix to solve y, b: identity matrix
#Ux=y to solve x ,x: inverse of A
I=np.identity(3)#b,identity matrix
Ai=np.zeros((3,3))#Ai is the y
A1=np.zeros((3,3))#A1 is the x
m,n=Ai.shape

print(Ai.shape)
#solve Ly=b ,Ai is y 
for j in range(0,n):
    for i  in range (0,n):
        Ai[i,j] = (I[i,j] - np.dot(L[i],Ai[:,j])) / L[i,i]
#solve Ux=y,A1 is x
for j in range(0,n):
    for i  in range (n-1,-1,-1):
        A1[i,j] = (Ai[i,j] - np.dot(Ab[i,i+1:n],A1[i+1:n,j])) / Ab[i,i]
print("The Ux=y is :\n",Ai)
print("The inverse of A is\n",A1)

(3, 3)
The Ux=y is :
 [[ 1.  0.  0.]
 [ 2.  1.  0.]
 [-1. -1.  1.]]
The inverse of A is
 [[-0.33333333  0.33333333 -0.66666667]
 [ 0.25        0.75       -1.25      ]
 [ 0.5         0.5        -0.5       ]]
