Numpy学习——数组填充np.pad()函数的应用

In [1]:
import numpy as np

1.1 常数填充模式——’constant'

In [2]:
A = np.arange(95,99).reshape(2,2)    #原始输入数组
A

array([[95, 96],
       [97, 98]])

In [3]:
np.pad(A,((3,2),(2,3)),'constant',constant_values = (0,0))

array([[ 0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0],
       [ 0,  0, 95, 96,  0,  0,  0],
       [ 0,  0, 97, 98,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0]])

1.在数组A的边缘填充constant_values指定的数值
2.（3,2）表示在A的第[0]轴填充（二维数组中，0轴表示行），即在0轴前面填充3个宽度的0，比如数组A中的95,96两个元素前面各填充了3个0；在后面填充2个0，比如数组A中的97,98两个元素后面各填充了2个0
3.（2,3）表示在A的第[1]轴填充（二维数组中，1轴表示列），即在1轴前面填充2个宽度的0，后面填充3个宽度的0

In [4]:
#填充时，从前面轴，往后面轴依次填充
np.pad(A,((3,2),(2,3)),'constant',constant_values = (-2,2))   #填充值，前面填充改为-2，后面填充改为2

array([[-2, -2, -2, -2,  2,  2,  2],
       [-2, -2, -2, -2,  2,  2,  2],
       [-2, -2, -2, -2,  2,  2,  2],
       [-2, -2, 95, 96,  2,  2,  2],
       [-2, -2, 97, 98,  2,  2,  2],
       [-2, -2,  2,  2,  2,  2,  2],
       [-2, -2,  2,  2,  2,  2,  2]])

In [5]:
np.pad(A,((3,2),(2,3)),'constant',constant_values = ((0,0),(1,2)))    #0轴和1轴分别填充不同的值，先填充0轴，后填充1轴，存在1轴填充覆盖0轴填充的情形

array([[ 1,  1,  0,  0,  2,  2,  2],
       [ 1,  1,  0,  0,  2,  2,  2],
       [ 1,  1,  0,  0,  2,  2,  2],
       [ 1,  1, 95, 96,  2,  2,  2],
       [ 1,  1, 97, 98,  2,  2,  2],
       [ 1,  1,  0,  0,  2,  2,  2],
       [ 1,  1,  0,  0,  2,  2,  2]])

1.2 边缘值填充模式——’edge'

In [6]:
B = np.arange(1,5).reshape(2,2)  #原始输入数组
B

array([[1, 2],
       [3, 4]])

In [7]:
np.pad(B,((1,2),(2,1)),'edge')   #注意先填充0轴，后面填充1轴，依次填充

array([[1, 1, 1, 2, 2],
       [1, 1, 1, 2, 2],
       [3, 3, 3, 4, 4],
       [3, 3, 3, 4, 4],
       [3, 3, 3, 4, 4]])

1.3 边缘最大值填充模式——’maximum’

In [8]:
B = np.arange(1,5).reshape(2,2)  #原始输入数组
B

array([[1, 2],
       [3, 4]])

In [9]:
np.pad(B,((1,2),(2,1)),'maximum')   

array([[4, 4, 3, 4, 4],
       [2, 2, 1, 2, 2],
       [4, 4, 3, 4, 4],
       [4, 4, 3, 4, 4],
       [4, 4, 3, 4, 4]])

In [10]:
C = np.arange(0,9).reshape(3,3)  #原始输入数组
C

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [11]:
np.pad(C,((3,2),(2,1)),'maximum')  

array([[8, 8, 6, 7, 8, 8],
       [8, 8, 6, 7, 8, 8],
       [8, 8, 6, 7, 8, 8],
       [2, 2, 0, 1, 2, 2],
       [5, 5, 3, 4, 5, 5],
       [8, 8, 6, 7, 8, 8],
       [8, 8, 6, 7, 8, 8],
       [8, 8, 6, 7, 8, 8]])