In [1]:
import numpy as np

n = 5
a = np.random.rand(n,n)*10-5 + np.eye(n)*10
I = np.eye(n)

A = a.copy()

for i in range(n):
  if A[i][i] == 0.0:
    sys.exit('Divide by zero detected!')
      
  for j in range(n):
    if i != j:
      ratio = A[j][i]/A[i][i]

      for k in range(n):
        A[j][k] = A[j][k] - ratio * A[i][k]
        I[j][k] = I[j][k] - ratio * I[i][k]

for i in range(n):
  divisor = A[i][i]
  for j in range(n):
    A[i][j] = A[i][j]/divisor
    I[i][j] = I[i][j]/divisor

print('原矩阵：\r\n',a)
print('\r\n')

print('变换后的矩阵 A：\r\n',A)
print('\r\n')

print('逆矩阵 I：\r\n',I)
print('\r\n')

print('验证 a 与变换后的 I 互为逆矩阵')
print(a @ I)

原矩阵：
 [[12.26005049 -3.67729707 -1.19053259  1.54496239  2.69009661]
 [ 4.27437626  6.9162511   1.07460466 -0.63832698 -4.10655273]
 [ 2.61130883 -2.90868386 14.21650739 -0.85925095 -4.54817992]
 [-1.50606478  3.6175164  -3.30743118 12.56171253 -0.41198703]
 [ 0.90654519  2.1233391   1.65273598  0.50447263 13.93856827]]


变换后的矩阵 A：
 [[ 1.00000000e+00  0.00000000e+00  0.00000000e+00  8.94527950e-18
   0.00000000e+00]
 [ 3.76971374e-18  1.00000000e+00  0.00000000e+00  3.76971374e-18
   0.00000000e+00]
 [ 3.03973028e-18  0.00000000e+00  1.00000000e+00  3.03973028e-18
   0.00000000e+00]
 [-6.75917132e-20  0.00000000e+00  0.00000000e+00  1.00000000e+00
   0.00000000e+00]
 [ 7.04004680e-18  0.00000000e+00  0.00000000e+00  7.04004680e-18
   1.00000000e+00]]


逆矩阵 I：
 [[ 0.06682112  0.03956215  0.00130671 -0.00607866 -0.00099382]
 [-0.03564967  0.10574503 -0.01318275  0.00749268  0.03395456]
 [-0.01787511  0.00693197  0.06653328  0.00600219  0.02737946]
 [ 0.01366023 -0.02449461  0.02124999  0

In [2]:
a=float(1)
b=float(0)
b/a

0.0