In [84]:
import numpy as np
from numpy import fabs
import sys

In [106]:
print("Input the dimension of matrix A: \n")
a,b = input().split()
a = int(a)
b = int(b)
print("Input matrix A: \n")
lst = []
for i  in range(a):
    x = [eval(i) for i in input().split()]
    lst.append(x)


Input the dimension of matrix A: 

3 3
Input matrix A: 

1 0 0
1 1 0
1 1 1


array([[1, 0, 0],
       [1, 1, 0],
       [1, 1, 1]])

In [107]:
a = np.array(lst)
U = np.array(a)
m,n = np.shape(U)

if(n>m) :
    n = n-1

for i in range(0,m-1):
    if U[i,i] == 0:
        for k in range(i+1,m):
            if fabs(U[k,i]) > fabs(U[i,i]):
                U[[i,k]] = U[[k,i]]
                break    
                
    for j in range(i+1,n):
        mul = U[j,i]/U[i,i]
        U[j,i:n+1] = U[j,i:n+1] - U[i,i:n+1]*mul
        
flag = 0
for i in range(m):
    if(U[i,i] == 0):
        print("Input error : Matrix A must be linearly independent columns !")
        flag = 1
        break
if flag == 1:
    sys.exit(0)


In [208]:
u1 = a.T[0]
u2 = a.T[1]
u3 = a.T[2]
print("u1 = ",u1)
print("u2 = ",u2)
print("u3 = ",u3)
U = np.concatenate((u1,u2,u3),axis = 0).reshape(m,n)

u1 =  [1 1 1]
u2 =  [0 1 1]
u3 =  [0 0 1]


In [151]:
v1 = u1
sum1 = 0
sum2 = 0

for i in range(m):
    sum1 += pow(v1[i],2)
v2 = u2 - np.dot(u2,v1)/sum1*v1

for i in range(m):
    sum2 += pow(v2[i],2)
v3 = u3 - (np.dot(u3,v1)/sum1*v1) - (np.dot(u3,v2)/sum2*v2)

print("v1 = ",v1)
print("v2 = ",v2)
print("v3 = ",v3)

v1 =  [1 1 1]
v2 =  [-0.66666667  0.33333333  0.33333333]
v3 =  [ 0.  -0.5  0.5]


In [162]:
sum3 = 0
for i in range(m):
    sum3 += pow(v3[i],2)
q1 = v1/pow(sum1,0.5)
q2 = v2/pow(sum2,0.5)
q3 = v3/pow(sum3,0.5)

print("q1 = ",q1)
print("q2 = ",q2)
print("q3 = ",q3)

q1 =  [0.57735027 0.57735027 0.57735027]
q2 =  [-0.81649658  0.40824829  0.40824829]
q3 =  [ 0.         -0.70710678  0.70710678]


In [209]:
Q = np.concatenate((q1.T,q2.T,q3.T),axis = 0)
Q = Q.reshape(3,3).T
R = np.zeros(n*m).reshape(3,3)
for i in range(m):
    for j in range(i,n):
        R[i,j] = U[j].dot(Q.T[i])
print("Q = \n",Q)
print("R = \n",R)

Q = 
 [[ 0.57735027 -0.81649658  0.        ]
 [ 0.57735027  0.40824829 -0.70710678]
 [ 0.57735027  0.40824829  0.70710678]]
R = 
 [[1.73205081 1.15470054 0.57735027]
 [0.         0.81649658 0.40824829]
 [0.         0.         0.70710678]]


In [210]:
print("A = \n",Q.dot(R))      

A = 
 [[1.00000000e+00 1.11022302e-16 5.55111512e-17]
 [1.00000000e+00 1.00000000e+00 1.99673462e-16]
 [1.00000000e+00 1.00000000e+00 1.00000000e+00]]
