In [1]:
import numpy as np

## import ... as ...
import 代表的是引入一個package(套件)，<br>
而as 代表的是取一個簡易的名稱避免原名稱過於冗長。

In [9]:
x,y,z=(input().split())
print(type(x),type(y),type(z))
x=int(x)
y=float(y)
z=int(z)
z=bool(z)
print(x,y,z)
print(type(x),type(y),type(z))

<class 'str'> <class 'str'> <class 'str'>
1 2.0 False
<class 'int'> <class 'float'> <class 'bool'>


In [6]:
a=0
a=bool(0)
a

False

## 型態 
string(字串)，就是把一堆字元串起來的意思，字元又是什麼呢？像是字母、數字、符號、空格或是換行都是字元。<br>
int(整數)，用來表示整數值。<br>
float(浮點數)，用來表示小數值。<br>
bool(布林值)，代表的是1(true)與0(false)，用來判斷語句的運算值為真或假。<br>
## 基礎語法
python 在輸入時input(輸入)皆默認為string(字串) 的型態。<br>
split() 用來把字串透過指定的分隔符號對字串進行分割，不給入參數的話，預設會以空白作為分隔符號做切割。<br>
'型態'()，代表的是強制轉換型態。<br>
type() 為用來查看資料型態的方法，class可視作一個類別的意思。<br>
input() 為輸入，print() 為輸出。


In [4]:
a=1
b=2
print(type(a),type(b))
print(a+b,type(a+b))
print(a-b,type(a-b))
print(a*b,type(a*b))
print(a/b,type(a/b))
print(a//b,type(a//b))
print(a%b,type(a%b))
print(a**b,type(a**b))
print(float(a),type(float(a)))

<class 'int'> <class 'int'>
3 <class 'int'>
-1 <class 'int'>
2 <class 'int'>
0.5 <class 'float'>
0 <class 'int'>
1 <class 'int'>
1 <class 'int'>
1.0 <class 'float'>


## 基礎語法
python會自動偵測型態，所以這裡的a,b 便會被判斷為int的型態。<br>
## 運算子
需要注意的是<br>
'/'為一般的除法概念，而'//'為整數除法也就是忽略小數點。<br>
'%'為求餘數。<br>
' ** '為次方意義，即a的b次方。<br>

In [5]:
a=0
if a>0:
    print('a>0')
elif a<0:
    print('a<0')
else:
    print('a=0')

a=0


## if ... else
if '條件句' :<br>
&emsp;'執行句'<br>
elif '條件句' :<br>
&emsp;'執行句'<br>
else:<br>
&emsp;'執行句'<br>

In [6]:
A=np.array(([1,2,3],[4,5,6]),float)
#A
print(A,type(A),A.dtype)

[[1. 2. 3.]
 [4. 5. 6.]] <class 'numpy.ndarray'> float64


## numpy 套件
np.array(): 建成一個矩陣，有矩陣加減乘除的應用<br>
後項的float是將每一個element強制轉換的意思。<br>
dtype:返回陣列中元素的資料型態。<br>
這邊的float64代表有8個bytes，8*8=64個bits。
## 基礎語法
可直接寫成A，或print(A)。

In [7]:
m,n=map(int,input().split())
matrix=np.zeros((m,n))
print(matrix,matrix.shape)

3 5
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] (3, 5)


## 基礎語法
map(function, iterable, ...):定義一個function。接著用這個function來對一個iterable 的物件內每一個元素做處理。<br>
在這邊，使用map函式第一個參數int，將第二個參數轉型成整數(int)。
## numpy 套件
np.zeros((m,n)):建成一個m個row、n個column，element全為0的矩陣。
shape:查看矩陣的row跟column。

In [8]:
num=10
for i in range(num):
    print(i)   

0
1
2
3
4
5
6
7
8
9


## for迴圈
i是從0開始到num-1，而不是到num。

In [9]:
B=np.array([1,2,3])
for i in range(len(B)):
    print(i)
    B[i]=2*B[i]
B

0
1
2


array([2, 4, 6])

## 基礎語法
len:返回的值為長度或項的個數。

In [10]:
A=np.array([1,2,3])
B=np.array([4,5,6])
print(A*B,type(A*B),(A*B).dtype)

[ 4 10 18] <class 'numpy.ndarray'> int32


## 矩陣乘法
使用' * '，表示矩陣內的每個element相乘。

In [11]:
C=A*B
print(C.astype(float),(C.astype(float)).dtype)

[ 4. 10. 18.] float64


## numpy 套件
astype:轉換資料的型態。

In [12]:
A.dot(B)
print(A.dot(B),type(A.dot(B)),(A.dot(B)).dtype)

32 <class 'numpy.int32'> int32


## numpy 套件
A.dot(B):代表矩陣的內積，亦可寫成np.dot(A,B)。

In [13]:
np.diag(A)

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

## numpy 套件
np.diag():將原本$1 \times 3$的A矩陣，形成$3 \times 3$以一維矩陣A的元素作為對角線上的矩陣。

In [14]:
D=np.array([1,2,3,4,5,6,7,8,9])
print(D,'\n',D.reshape(3,3),'\n',np.diag(D.reshape(3,3)))

[1 2 3 4 5 6 7 8 9] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
 [1 5 9]


## numpy 套件
reshape:對有n個element的矩陣，重塑陣列形狀，需化為擁有相同數量(即$row \times column$=n)的element的矩陣。<br>
np.diag():若對一個不為一維矩陣的使用np.diag()，會變成提取對角線上的元素。